"""initial_schema

Revision ID: f24c87421d9e
Revises:
Create Date: 2026-06-30 06:20:03.666913

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f24c87421d9e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "horses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("role_scopes", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "baselines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("horse_id", sa.Integer(), nullable=False),
        sa.Column("feature_name", sa.String(length=60), nullable=False),
        sa.Column("median", sa.Float(), nullable=False),
        sa.Column("mad", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["horse_id"],
            ["horses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("horse_id", "feature_name", name="uq_baseline_feature"),
    )
    with op.batch_alter_table("baselines", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_baselines_horse_id"), ["horse_id"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("horse_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("surface", sa.String(length=80), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("stopped_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.Enum("DRAFT", "COMPLETED", name="sessionstatus"), nullable=False),
        sa.Column("is_baseline", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["horse_id"],
            ["horses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feature_windows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("ts_start", sa.BigInteger(), nullable=False),
        sa.Column("ts_end", sa.BigInteger(), nullable=False),
        sa.Column("cadence_spm", sa.Float(), nullable=True),
        sa.Column("stride_var", sa.Float(), nullable=True),
        sa.Column("asymmetry_proxy", sa.Float(), nullable=True),
        sa.Column("energy", sa.Float(), nullable=True),
        sa.Column("quality_flags", sa.String(length=160), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "ts_start", name="uq_window_unique"),
    )
    with op.batch_alter_table("feature_windows", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_feature_windows_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_feature_windows_ts_start"), ["ts_start"], unique=False)

    op.create_table(
        "sensor_readings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("ts_ms", sa.BigInteger(), nullable=False),
        sa.Column("ax", sa.Float(), nullable=False),
        sa.Column("ay", sa.Float(), nullable=False),
        sa.Column("az", sa.Float(), nullable=False),
        sa.Column("gx", sa.Float(), nullable=False),
        sa.Column("gy", sa.Float(), nullable=False),
        sa.Column("gz", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "ts_ms", name="uq_reading_session_ts"),
    )
    with op.batch_alter_table("sensor_readings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sensor_readings_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_sensor_readings_ts_ms"), ["ts_ms"], unique=False)

    op.create_table(
        "anomalies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("window_id", sa.Integer(), nullable=False),
        sa.Column("method", sa.Enum("STATS", "FUSION", name="anomalymethod"), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("severity", sa.Enum("LOW", "MEDIUM", "HIGH", name="severity"), nullable=False),
        sa.Column("details_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["window_id"],
            ["feature_windows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("window_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("anomalies")
    with op.batch_alter_table("sensor_readings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sensor_readings_ts_ms"))
        batch_op.drop_index(batch_op.f("ix_sensor_readings_session_id"))

    op.drop_table("sensor_readings")
    with op.batch_alter_table("feature_windows", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feature_windows_ts_start"))
        batch_op.drop_index(batch_op.f("ix_feature_windows_session_id"))

    op.drop_table("feature_windows")
    op.drop_table("sessions")
    with op.batch_alter_table("baselines", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_baselines_horse_id"))

    op.drop_table("baselines")
    op.drop_table("users")
    op.drop_table("horses")
    # ### end Alembic commands ###
